### PR TITLE
Update 02_13_batch-effects.Rmd

### PR DESCRIPTION
**Pull request by PeteHaitch**
Typo

### CODE REVIEW

**Comment by jtleek** [comment]
Pete you are a baller, thanks so much for helping out!

**Comment by PeteHaitch** [comment]
Hoping to help out much more when I finally get to Bmore!

**Comment by jtleek** [comment]
That's soon I hope ?

**Comment by PeteHaitch** [comment]
Hopefully. I should be able to get the visa application rolling next week.
It only took 3 or so weeks for a mate to get his sorted

**Pull request merged**
